# This is a basic workflow to help you get started with Actions



name: Node.js CD



# Controls when the action will run. 

on:

  # Triggers the workflow on push or pull request events but only for the master branch

  push:

    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest



    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

    - name: Deploy using ssh

      uses: appleboy/ssh-action@master

      with:

        host: ssh.sanchyan.tech

        username: sourav

        key: "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDQgGnQrhaid7AfY9AF81t+AAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDIVmfiPTtdwDAFnL4mfMwnGifyP13qyGe+y76VmKbX+WwwOqw+n3PMjfy8qbTTMW8ya/jn3meFZVG2+ycDdLyTPYCYl9iwJ4Ubin7ElPhw+VbwLW5zxhJlGMi5tsu/BuxNv1TTXS55xQdLjMzyDBhBJEm8cRqSsiU6D73YplQwq27x2sg6tKHvcr/e67yLBubANgJnDzLTGlXw6BsalmcXEGJFArQpy4QxmF0JfooMMnn4ac7JIq+OwXDr4pjoSbKxP9q9o0e5doZIo8Lqr9KY0IofWmQOXpOk6XiY+iMlmtq7vPydwyh4pOCLkU8m1i+n504IR/5eZbF9MOSRl6j0Ltpxu5ZSE7f/KlkGCCKCLe5R+kF4e8MdKH3s4rPjB3Jeoh41VTDSdOiKxn1smL+X9qlmRROG7A0qxJUjuKuyzgjseoPF9cQ2bIcl7AbHeppt2yA9ceAQlogWynYJb/UFdI6O5EThphhQSH8bGaehskHxncp5Ev0M5i7FSjzmCd0AAAWQEJpKPCbB+zKNVCAaXqnYqW3wmReH1CTrC3BnwX74jcGiOTbSlIAVgd4OITP6iF9e53ba8vYyE34CS+ZMqfgkraXRmEEFYQsPa5QiOHvSe+GJ00yLag5Fb1g6GeIBT2EZxuEeidCkBGRGUUVnPrlBeKqMU2XadedYLD9KgMKWpVTDmuj2pnCdi5+Dv9VD6cR6TZYm83Ochh5swP8IrTeCdF7wVBRiXlcz3aLbr1cFPT6UvzuNwjbEv0a2wHPC8gmNes/cU3G31Gq89+ZfYgq/rt0GAJf88U1Fw4o44D9Sw+KdhvElCpc8mJ2iIBgZ2Nux6GIAKvZoyY+jHPbJxdKUhTUVEEAfytzmmMc0eGg3mVvzVOSkjzi1t4+7qwWda+ysyYfl1m9BrLmFeSM0jDYnhoWoyRMbWx4+K4f1IOj0E4nfVH5nlLBERH77+Y9YaiJWIqisO0UYpTkA/tWrAqK03TEvoBuh8OwnKZIUvj+3lwZKWNG5bdIbuvsCbimaCqkuyZp182DYQIO1RautrfIHIsALYDMdrU/5SunMWxk6dgieGyJXhFk+CFA/eGShVIa25poTlSt+EplVEEXILoHohWxSJtBlK9G/RNlyBkryCWHo+DArbgcOqqd1HLhqcE8lSrLnlgVSVKZyyQok3D+zHplk35zu3UsEm/wri/oOooOP2T2EA5r66YPR7mh5So/bXdmiyMpxrt7ZzjbhEPsUZSDB5oGc5KfenftcGHYJOMKKZ7zU6V6GN/NpuABeScFJRGso7yjJ1npjwVt9b4rH6tRpw9rhegPeSQg+cSofMxcisE8jiMqkdamJDqlwfNCTDDmpP2XTTXpQ4mU8+tVjvbH/od1h47JlW8Wov5swQji3ekj571OyMvZppzupbOfWVGL9cFFNWGoLOVe5yPgxVvl+r+vAKHw6CpYfWLzbkdNQb/tSrvuuAxdBMkDJgUdhnh5tM7SiZzm6ZOAH59P8eLVVZ8+yKqFF7ci5p5XD3mzZu15sLtcpA0wa8k3i2Q3SHn6RVXqMMWav2ZSjhz1Hgr5FHFhp4DvElBPedxpaLuJ9pSID4BMRlKto5SV72Ya6EW5Sm7Rh+ega+ID/0y6l2JSLZDCKISOW1As+66jDisYWb7rUNzsaWhHx7hYtnsMyc1wS17iUcPVVkAexfBcwP0ViAg11z5z2Y+aaL610/pEqA2nIyXI5WMeGz/zXzMkp/dIKgD4faUheuNzBnbYCoNIzJ4LgHpZBCXf4KYF3gNTvOylkyROJbSr3H/JLTY6fBeC2JsvdCksne4TITgjsp0YUPIwK1HGoC6QQ2ZQPIpyAQET/KBTtk2BlZHASYARjqcOXNDZGcgqIDciaTOJJrHyK9AilNU390YtTanOwJECmX+u7bsrGqbV8kmGNyoHx9T4siRl5z7dzoGzzS2b0AqwNNdwM++t9sU0u5H56c3pQ3Jby/peQbJh6VoEW2o+mVDrFGeKRfaqPXvUWIXhnffGL7bf2HL6Sj8H71/d1QJdCpH/ERC1MAy6pixhk8kKLLoVC0hU/LxFFa7V664GJ4cae1jy9bMEv8qO9C9ii81Jc5zluyHDwDKya1eHDnlFSweBSD0Wm8k+AdUc7fa/f3RW3jU4mmN1kwDLitCVqQqESQsCFX2mZCaRsi+3DyFpCiAaVZ3cXlHWaPgHKJwwqWDgj8hEzj91U7TD0ukGdq8tAuc1A75EwkjcdCjY+SCt+V38ntszRw0fWGUd2H75Mq178E3QrNxiEbbjmXqLbGkqeMK+EsyJPA84WmtL5KnNn4w4xIvpuf/ek4qzOkYOnVwtxayOvZ+uHKAtqggvDZs2/2G5CE8smuS/p2+AkdqltYzdyW80xEsI5WntWW+JTTWXvuZIiyVXKxWikB0afSI0=-----END OPENSSH PRIVATE KEY-----"

        port: 8080

        script: |

          cd groceryji/grocery-app

          git pull origin master

          git status
